version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads:rw
